### ISSUE TITLE
Chat emoji popup is difficult to see

### ISSUE THREAD

**Issue by Ringlings** [LeafyLuigi/discord-themes#3]
Exactly as the title says, this popup doesn't seem to have any blur and is difficult to see

![image](https://user-images.githubusercontent.com/110815694/214475946-3c195962-da3d-41f4-944d-462e7581dd45.png)

Not sure if this is the right place for this issue, sorry
~~Also don't ask why there's so many of that emoji~~

**Comment by LeafyLuigi** [comment]
Either here or on the support server is fine. I've got a webhook hooked up to this repo.

I forgot to add a blur to the that modal. The light theme also needs a bit of an overhaul to make sure the contrast of the backgrounds aren't so similar.

**Comment by Ringlings** [comment]
Yeah we can definitely see the contrast difficulties but they're not as *bad* as this
Other than that love the theme, by the way
