### ISSUE TITLE
How to change the image of a page to a local one?

### ISSUE THREAD

**Issue by Edwin38H** [LeafyLuigi/discord-themes#4]
Inside the downloadable .css themes there are images with url, I want to change it to images with local addresses but I don't know how to do it

**Comment by LeafyLuigi** [comment]
You'll need to find a plugin or create a server that allows usage of locally hosted images. Unfortunately, I can't suggest any as _I don't know any_.

An alternative is to use a [data URI](https://css-tricks.com/data-uris/) which won't require any plugins at all. The attached link has instructions on how to do it.
