### ISSUE TITLE
OG Pyrite theme

### ISSUE THREAD

**Issue by HUIHUILORD** [LeafyLuigi/discord-themes#5]
Does anyone have a file link for the OG version of pyrite theme i honestly liked that way better and want to use it but I can't find it anywhere

**Comment by LeafyLuigi** [comment]
[It still exists.](https://github.com/LeafyLuigi/discord-themes/blob/master/pyrite/pyrite-synthscape-orange.theme.css) Click "Raw" then press CTRL+S (or CMD+S if you're using a Mac) and save it in the themes folder.
